version: 0.2

env:
  shell: bash
  git-credential-helper: "yes"
  exported-variables:
    - LAMBDA_ARNS
    - API_ENDPOINT
    - BUILD_COLOR

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 14
    commands:
      - pip3 install --upgrade pip
      - pip3 install -r requirements.txt >/dev/null
  pre_build:
    commands:
      - make
      - echo "###########################################"
      - echo "# - Assume Role for Cross Account to (empty if dev)"
      - $PROD_ASSUME_ROLE
      - "echo ###########################################"
  build:
    commands:
      - echo "###########################################"
      - echo "# Deploy CDK"
      - cdk $CDK_ACTION $STACK_TO_DEPLOY $DEPLOYMENT_TAG $USE_PROD_VALUES --require-approval never --force --outputs-file ./cdk-outputs.json
      - export API_ENDPOINT=$(jq -r '.. | objects |.ApiEndpoint | select(.!=null)' ./cdk-outputs.json)
      - export API_DOMAIN=$(jq -r '.. | objects |.ApiDomainName | select(.!=null)' ./cdk-outputs.json)
  post_build:
    commands:

artifacts:
  files: "**/*"
